"""Brief template and generation utilities."""

from dataclasses import dataclass
from typing import Any


@dataclass
class BriefSection:
    """A section of the research brief."""

    title: str
    content: str
    citations: list[str] = None

    def __post_init__(self):
        if self.citations is None:
            self.citations = []


class BriefTemplate:
    """Template for research briefs."""

    @staticmethod
    def get_markdown_template() -> str:
        """Get the Markdown template for research briefs."""
        return """# Research Brief: {title}

**Generated**: {date}
**Topic**: {topic}
**Papers Analyzed**: {paper_count}

---

## Executive Summary

{executive_summary}

---

## Key Findings by Theme

{key_findings}

---

## Areas of Consensus

{areas_of_consensus}

---

## Areas of Conflict

{areas_of_conflict}

---

## Open Questions & Evidence Gaps

{evidence_gaps}

---

## Recommended Next Papers

{recommended_papers}

---

## Methodology

This research brief was generated using an AI-powered research synthesis pipeline:

1. **Paper Discovery**: Automated search of arXiv and Semantic Scholar
2. **Document Ingestion**: Full-text PDF extraction and structured field parsing
3. **Claim Extraction**: LLM-powered extraction of findings, hypotheses, and limitations
4. **Cross-Source Synthesis**: Thematic clustering and consensus analysis
5. **Brief Generation**: Structured synthesis with traceable citations

---

## References

{references}

---

*This brief was generated by the AI Research Synthesis Engine.*
"""

    @staticmethod
    def format_theme_section(theme: dict) -> str:
        """Format a single theme section."""
        theme_name = theme.get("theme_name", "Unknown Theme")
        claims = theme.get("claim_ids", [])
        consensus = theme.get("consensus", "unknown")
        summary = theme.get("summary", "")

        consensus_badge = {
            "strong": "🟢 Strong Consensus",
            "moderate": "🟡 Moderate Consensus",
            "weak": "⚪ Weak Consensus",
            "conflicting": "🔴 Conflicting",
        }.get(consensus, consensus)

        lines = [
            f"### {theme_name} {consensus_badge}",
            "",
            summary,
            "",
            f"**Claims**: {len(claims)}",
            "",
        ]

        return "\n".join(lines)

    @staticmethod
    def format_apa(paper: dict) -> str:
        """Format paper as APA citation."""
        return CitationFormatter.format_apa(paper)

    @staticmethod
    def format_claim_with_citation(claim: dict, paper: dict) -> str:
        """Format a claim with its citation."""
        claim_text = claim.get("claim_text", "")
        claim_type = claim.get("claim_type", "").upper()
        source_section = claim.get("source_section", "")
        source_location = claim.get("source_location", "")

        paper_title = paper.get("title", "Unknown")[:60]
        paper_id = paper.get("paper_id", "")

        lines = [
            f"- **[{claim_type}]** {claim_text}",
            f"  - Source: *{paper_title}...* ({source_section}, {source_location})",
            f"  - Ref: [{paper_id}]",
        ]

        return "\n".join(lines)


class CitationFormatter:
    """Format citations in various styles."""

    @staticmethod
    def format_bibtex(paper: dict) -> str:
        """Format paper as BibTeX entry."""
        paper_id = paper.get("paper_id", "unknown").replace(":", "_").replace("/", "_")
        title = paper.get("title", "Unknown Title")
        authors = paper.get("authors", [])
        year = paper.get("year", "2024")

        author_str = " and ".join(authors[:3])
        if len(authors) > 3:
            author_str += " et al."

        lines = [
            f"@article{{{paper_id},",
            f"  title = {{{title}}},",
            f"  author = {{{author_str}}},",
            f"  year = {{{year}}},",
            f"  url = {{{paper.get('url', '')}}},",
            "}",
        ]

        return "\n".join(lines)

    @staticmethod
    def format_apa(paper: dict) -> str:
        """Format paper as APA citation."""
        authors = paper.get("authors", [])
        year = paper.get("year", "2024")
        title = paper.get("title", "Unknown Title")

        if authors:
            author_str = f"{authors[0].split()[-1]}"
            if len(authors) > 1:
                author_str += f" & {authors[1].split()[-1]}"
            if len(authors) > 2:
                author_str += " et al."
        else:
            author_str = "Unknown"

        return f"{author_str} ({year}). {title}."

    @staticmethod
    def format_inline_citation(paper: dict) -> str:
        """Format as inline citation."""
        authors = paper.get("authors", [])
        year = paper.get("year", "n.d.")

        if authors:
            first_author = authors[0].split()[-1]
            if len(authors) > 1:
                return f"({first_author} et al., {year})"
            return f"({first_author}, {year})"

        return f"(Unknown, {year})"
